import type { Messages } from './types';

export const en: Messages = {
  common: {
    save: 'Save',
    cancel: 'Cancel',
    create: 'Create',
    add: 'Add',
    remove: 'Remove',
    custom: 'Custom',
    total: 'Total',
    copied: 'Copied!',
    copyText: 'Copy Text',
    exportCsv: 'Export CSV',
    ppm: 'ppm',
    mePerL: 'me/L',
  },

  app: {
    title: 'Nutrient Calculator',
    fullTitle: 'Hydroponic Nutrient Calculator',
    toggleTheme: 'Toggle theme',
    switchToDark: 'Switch to dark mode',
    switchToLight: 'Switch to light mode',
  },

  nav: {
    recipeBrowser: 'Recipe Browser',
    targetSolver: 'Target Solver',
    tools: 'Tools',
  },

  recipe: {
    presetRecipe: 'Preset Recipe',
    builtIn: 'Built-in Recipes',
    saved: 'Saved Recipes',
    saveRecipe: 'Save Recipe',
    recipeName: 'Recipe name...',
  },

  chemical: {
    title: 'Chemicals (mg/L)',
    addPlaceholder: 'Add a chemical...',
    chemical: 'Chemical',
  },

  ions: {
    title: 'Ion Concentrations',
    ion: 'Ion',
    delta: 'Delta',
    macro: 'Macronutrients',
    micro: 'Micronutrients',
    estEc: 'Est. EC',
    range: (low, high) => `Range: ${low}\u2013${high} ppm`,
  },

  balance: {
    title: 'Cation-Anion Balance',
    cations: 'Cations',
    anions: 'Anions',
    ratio: 'Ratio',
    status: 'Status',
    ideal: 'Ideal: 1.00 : 1',
    balanced: 'Balanced',
    cationExcess: 'Cation excess',
    anionExcess: 'Anion excess',
    perfect: 'Perfect',
    deviation: (pct) => `${pct}% deviation`,
  },

  ratios: {
    title: 'Nutrient Ratios',
    macroBalance: 'Macronutrient balance',
    caMgIdeal: 'Ideal range: 2:1 to 5:1',
    no3nh4Prefer: 'Most crops prefer >8:1',
    allNO3: '100% NO\u2083',
    noAmmonium: 'No ammonium nitrogen',
    fruitingKCa: 'Fruiting crops: ~1.5:1',
  },

  volume: {
    title: 'Mixing Amounts',
    waterVolume: 'Water volume:',
    liters: 'liters',
  },

  water: {
    title: 'Water Profile',
    subtracting: 'Subtracting',
    off: 'Off',
    sourceName: 'Water source name...',
    description: 'Enter your tap/source water ion concentrations. These will be subtracted from recipe targets.',
  },

  ph: {
    title: 'pH Adjustment Calculator',
    description: 'Calculate the ion impact of adding acid or base to your reservoir.',
    acids: 'Acids',
    bases: 'Bases',
    volumeAdded: 'Volume added',
    concentration: 'Concentration',
    reservoir: 'Reservoir',
    result: (g, formula, liters) => `Adding ${g} g of ${formula} to ${liters} L`,
  },

  stock: {
    title: 'A/B Stock Solution',
    emptyDescription: 'Add chemicals to your recipe first, then calculate stock solutions here.',
    description: 'Separate chemicals into A/B tanks to avoid calcium precipitates. Tank A: calcium + iron. Tank B: sulfates + phosphates.',
    concentration: 'Concentration',
    tankVolume: 'Tank volume',
    dilute: (mL, liters) => `Dilute: add ${mL} mL stock per ${liters} L water`,
    tankA: 'Tank A \u2014 Calcium + Iron + Nitrates',
    tankB: 'Tank B \u2014 Sulfates + Phosphates',
    noChemicals: 'No chemicals in this tank',
  },

  solver: {
    targetConcentrations: 'Target Concentrations (ppm)',
    clearAll: 'Clear all',
    macronutrients: 'Macronutrients',
    micronutrients: 'Micronutrients',
    availableChemicals: 'Available Chemicals',
    macroSalts: 'Macro Salts',
    microSalts: 'Micro Salts',
    acidsAndBases: 'Acids & Bases',
    calculateOptimal: 'Calculate Optimal Amounts',
    recommendedAmounts: 'Recommended Chemical Amounts',
  },

  breakdown: {
    title: 'Per-Chemical Breakdown (ppm)',
    chemical: 'Chemical',
  },

  export: {
    header: '=== Hydroponic Nutrient Solution ===',
    chemicalsSection: '--- Chemicals (mg/L) ---',
    ecSection: (ec) => `--- EC: ${ec} mS/cm ---`,
    ionSection: '--- Ion Concentrations ---',
    columnHeaders: `${'Ion'.padEnd(16)} ${'ppm'.padStart(10)} ${'me/L'.padStart(10)}`,
    footer: 'Generated by Hydroponic Nutrient Calculator',
    csvHeader: 'Section,Name,Value,Unit',
    csvChemical: 'Chemical',
    csvEc: 'EC',
    csvEstimatedEc: 'Estimated EC',
    csvIon: 'Ion',
  },

  recipes: {
    hoagland: {
      name: 'Hoagland Solution',
      description: 'Classic full-strength Hoagland solution \u2014 general purpose reference.',
    },
    lettuce: {
      name: 'Lettuce',
      description: 'Optimized for head and leaf lettuce \u2014 moderate EC.',
    },
    'leafy-greens': {
      name: 'Leafy Greens',
      description: 'Balanced formula for spinach, kale, chard, and other leafy greens.',
    },
    tomato: {
      name: 'Tomato',
      description: 'High-K formula for tomato fruiting stage \u2014 higher EC.',
    },
    strawberry: {
      name: 'Strawberry',
      description: 'Moderate-K, higher Ca formula for strawberry production.',
    },
  },

  chemicals: {
    'calcium-nitrate': 'Calcium Nitrate Tetrahydrate',
    'calcium-nitrate-anhydrous': 'Calcium Nitrate (Anhydrous)',
    'potassium-nitrate': 'Potassium Nitrate',
    'monopotassium-phosphate': 'Monopotassium Phosphate',
    'monoammonium-phosphate': 'Monoammonium Phosphate (MAP)',
    'monocalcium-phosphate': 'Monocalcium Phosphate Monohydrate',
    'magnesium-sulfate': 'Magnesium Sulfate Heptahydrate (Epsom Salt)',
    'magnesium-sulfate-anhydrous': 'Magnesium Sulfate (Anhydrous)',
    'potassium-sulfate': 'Potassium Sulfate',
    'potassium-chloride': 'Potassium Chloride',
    'calcium-chloride': 'Calcium Chloride (Anhydrous)',
    'calcium-chloride-dihydrate': 'Calcium Chloride Dihydrate',
    'magnesium-nitrate': 'Magnesium Nitrate Hexahydrate',
    'fe-edta': 'Sodium Iron EDTA Trihydrate',
    'fe-dtpa': 'Sodium Iron(III) DTPA',
    'ferric-tartrate': 'Ferric Tartrate',
    'boric-acid': 'Boric Acid',
    'manganese-sulfate': 'Manganese Sulfate Monohydrate',
    'manganese-chloride': 'Manganese Chloride Tetrahydrate',
    'zinc-sulfate': 'Zinc Sulfate Heptahydrate',
    'copper-sulfate': 'Copper Sulfate Pentahydrate',
    'sodium-molybdate': 'Sodium Molybdate Dihydrate',
    'ammonium-heptamolybdate': 'Ammonium Heptamolybdate Tetrahydrate',
    'ammonium-molybdate': 'Ammonium Molybdate',
    'molybdic-acid': 'Molybdic Acid Monohydrate',
    'potassium-silicate': 'Potassium Silicate',
    'nitric-acid': 'Nitric Acid',
    'phosphoric-acid': 'Phosphoric Acid',
    'sulfuric-acid': 'Sulfuric Acid',
    'potassium-hydroxide': 'Potassium Hydroxide',
    'calcium-hydroxide': 'Calcium Hydroxide',
    'potassium-carbonate': 'Potassium Carbonate',
  },
};
